#
# Package makefile for the vlc.net.content.image directory
#

PACKAGE = vlc.util

SOURCE = Queue.java \
		 BlockingQueue.java \
		 TwoWayHashMap.java \
         IntHashMap.java

include ${PROJECT_ROOT}/make/Makefile.java
