#
# Package makefile for the vlc.net.content.image directory
#

PACKAGE = vlc.util.resource

SOURCE = ClassHashMap.java \
         Node.java \
         SingleMapHashMap.java \
         ResourceConstants.java \
         ManagerUtils.java \
         ResourceManager.java \
		 ResourceUtils.java \
		 ConfigLoader.java \
         TestResourceManager.java

include ${PROJECT_ROOT}/make/Makefile.java
