#
# Makefile for producing the JAR file used by this library
#

# No need to put in subdirs here. We only do that if we want to explicitly
# exclude some directory and then we name everything around it.
JAR_CONTENT=vlc/util \
            vlc/gui

# Manifest file name. Stored in the src/java directory
MANIFEST=

include ${PROJECT_ROOT}/make/Makefile.java
