#*********************************************************************
#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#*********************************************************************

PACKAGES = \
	 vlc.util \
	 vlc.util.resource \
     vlc.gui.layout

NODOC_PACKAGES = \

JARS =

JARS_3RDPARTY=

MAIN_CLASS     = 
MAIN_PACKAGE   = 
MAIN_JAR       = vlc_common.jar

#*********************************************************************
#
# Javadoc
#
#*********************************************************************

WINDOWTITLE = 'VLC Common Code Specification'
DOCTITLE    = 'VLC Classes API'
HEADER      = 'VLC Classes API'
BOTTOM      = '<font size=2>Copyright &copy; 2000 - \
		       <a href=\"http://www.vlc.com.au\">The Virtual Light Company</a> \
               </font>'

include $(PROJECT_ROOT)/make/Makefile.java 
