#
# Package makefile for the vlc.net.content.image directory
#

PACKAGE = vlc.gui.layout

SOURCE = LayoutManager3.java \
		 PositionConstraints.java \
		 PositionLayout.java

include ${PROJECT_ROOT}/make/Makefile.java
